### ISSUE TITLE
Issue with ImageData (Chrome)

### ISSUE THREAD

**Issue by jluengo13** [bradley/Blotter#24] opened 2018-02-22 03:45 UTC
'ImageData': The input data length is not a multiple of 4.

**Comment by controversial** [comment] 2018-03-03 20:53
Duplicate of #15

**Comment by bradley** [comment] 2018-11-28 00:39
Sorry everyone. I merged https://github.com/bradley/Blotter/pull/34 which should fix that. I didnt make the effort to semvar it and for that I am also sorry. If I or some helpful person ever gets around to putting it on NPM we'll have to be more serious about that.

**Closed by bradley** 2018-11-28 00:39 UTC
